### PR TITLE
Add @discardableresult

### PR DESCRIPTION
**Pull request by MatrixSenpai**
Swift's `@discardableresult` feature is useful for silencing compiler warnings when the result of `go()` or `go(with:)` is unused. This also surpresses the need to use `_ = cli.go()` and is the more "Swifty" way of doing things

### CODE REVIEW

**Comment by MatrixSenpai** [comment]
Pinging @jakeheis

**Comment by jakeheis** [comment]
If you can remove the committed `.swiftpm` files, I'll go ahead and merge this!

**Comment by MatrixSenpai** [comment]
@jakeheis done as requested

**Comment by jakeheis** [comment]
Looks good, thanks for the contribution!

**Pull request merged**
