### PR TITLE
Implement LineStream as easy to way to read written data line by line

### PR DESCRIPTION
**Pull request by jakeheis**

### CODE REVIEW

**Comment by yonaskolb** [comment]
I'm getting weird behaviour if creating more than one of these, even after the first one has finished. Nothing prints to the second one. Is it because something isn't being closed?

**Comment by jakeheis** [comment]
Hm could you give a code example? It works for me when I create two line streams, one for `stdout` and one for `stderr` as well as if I create two sequentially:

```swift
let out = LineStream { (line) in
    print("out", line)
}

let task = Task(executable: "cat", args: ["Package.swift"], stdout: out)
XCTAssertEqual(task.runSync(), 0)
out.wait()

let next = LineStream { (line) in
    print("next", line)
}

let task2 = Task(executable: "cat", args: ["LICENSE"], stdout: next)
XCTAssertEqual(task2.runSync(), 0)
next.wait()

```

**Comment by jakeheis** [comment]
@yonaskolb any more details on this? Haven't been able to recreate the issue

**Comment by yonaskolb** [comment]
Hi @jakeheis, sorry I haven’t had time to put together a test case for this.
From your tests it seems to be working well enough. 
It might be another case of a command that doesn’t flush its output working incorrectly

**Comment by jakeheis** [comment]
Gotcha that could be. Just for completion's sake, here is the other test I used which worked correctly:

```swift
let out = LineStream { (line) in
    print("out: '\(line)'")
}
let err = LineStream { (line) in
    print("err: '\(line)'")
}
let task = Task(executable: "/bin/bash", args: ["-c", "echo yo && echo sup >&2"], stdout: out, stderr: err)
task.runSync()
out.wait()
err.wait()
```

I'm going to go ahead and merge this in, but if you encounter any problems with it of course feel free to open an issue!

**Pull request merged**
