### PR TITLE
Print description in command help

### PR DESCRIPTION
**Pull request by yonaskolb**
This adds the command description to it's help output

### CODE REVIEW

**Comment by jakeheis** [comment]
Command description should definitely be included in the help message -- I think it should be after the usage line though, that way it will have the same format as the CLI usage statement.

```swift
~ > ice

Usage: ice <command> [options]

ice package manager

Groups:

...

~ > ice build --help

Usage: ice build [options]

**Command description here**

Options:

...

```

**Comment by yonaskolb** [comment]
Yeah ok 👍
Also maybe we could have a `longDescription` for commands. If will show the long otherwise the short. This would let you describe the parameters as well, but still keep a short description for the command list. What do you think?

**Comment by jakeheis** [comment]
That sounds great to me! I think that's the best solution to #61 as well

**Comment by jakeheis** [comment]
Thanks for this, looks great!

**Pull request merged**
