### PR TITLE
Allow Customization of Command Signature.

### PR DESCRIPTION
**Pull request by Lord-Kamina**
By turning into a protocol and using a placeholder variable for the parameter, it’s possible to create extension protocols and subclasses to define customized command signatures that may implement additional logic or alternate syntaxes.

### CODE REVIEW

**Comment by jakeheis** [comment]
I'm all for the idea of changing `CommandSignature` to a protocol, but I think a better approach than this placeholder approach would be to include within the protocol definition:
```swift
public protocol CommandSignature {
     init(signature: String)
     ...
```
And then within CLI:
```swift
public static var commandSignature: CommandSignature.Type = DefaultCommandSignature.self

...
private static func parseArguments(command: Command, arguments: RawArguments) throws -> CommandArguments {
    let commandSignature = self.commandSignature.init(signature: cmd.signature)
    ...
```

This is just rough code (haven't tried to compile any of it) but this approach would make the somewhat confusing `CLI.placeholder` unnecessary

**Comment by Lord-Kamina** [comment]
Yeah I actually noticed I have to toy around with it a bit more anyway,
after what appeared to work at first, I began running into some unexpected
issues later. I'll keep working on it and see what I can come up with.

-- 
Gregorio Litenstein Goldzweig
[image: glit_ind.png]
Médico Cirujano



   - Fono: +56 9 96343643 <+56%209%2096343643>
   - E-Mail: g.litenstein@gmail.com

**Comment by Lord-Kamina** [comment]
I took your advice into account; and, again, it's not exactly tidy but t works.
The way you'd implement a custom signature with this approach is:

``` Swift
public protocol ExtendedCommandSignature: CommandSignature {

    var aDifferentKindofParameter: [String] { get set }
    //... whatever else
}

protocol AnotherArgumentParser: CommandArgumentParser {
    func custom_parse(rawArguments: RawArguments, with signature: ExtendedCommandSignature) throws -> [String: Any]
}

// Note, I am using open because even though I'm keeping sources in different folders, the extended signature needed SwiftCLI membership, but I'm using it on a different target. 

open class CustomCommandSignature: ExtendedCommandSignature {

    var aDifferentKindofParameter: [String] = []
 	// Rest of custom signature code...   
}

open class CustomArgumentParser: AnotherArgumentParser { 

	public init () {} // This is also a needed workaround only because of the way I've structured my targets.
	
    public func parse(rawArguments: RawArguments, with signature: CommandSignature) throws -> [String : Any] {
        let signature = signature as! ExtendedCommandSignature
        return try custom_parse(rawArguments: rawArguments, with: signature)
    }
    
    public func custom_parse(rawArguments: RawArguments, with signature: ExtendedCommandSignature) throws -> [String: Any] {
    
    	// Actual Custom Command Parser Code...
    
    
    }
} 
```

As for the other commit, it's not really related to this particular feature, but basically it allows people to create aliases to commands including arguments and/or options so basically aliases can actually work as shortcuts for commonly used combinations.

**Comment by jakeheis** [comment]
New implementation, see #30 and `opt_groups` branch

**Pull request closed without merging**
